name: worldwide_channel_surf
description: An International Channel Browser with smart VPN routing based on user location.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.2
  openvpn_flutter: ^1.3.0
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.1
  http: ^1.1.0
  cached_network_image: ^3.3.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

